import "./globals.css";
import { Metadata } from "next";
import { ReduxProvider } from "@/store/provider";
import Layout from "@/components/layout/Layout";

export const metadata: Metadata = {
  title: "Made Apliances",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Layout>{children}</Layout>
        </ReduxProvider>
      </body>
    </html>
  );
}
